---
title: "Enrichment analysis For Fig. 8, Table S7"
author: "xyz"
date: "2020/5/12"
output: html_document
---

### To obtain the abundance differential protein

```{r}
suppressMessages(library(dplyr))

df<-openxlsx::read.xlsx("PanamaNCBI2ProteinsFix.xlsx")
df<-filter(df,Contaminant==F,`Exp..q-value:.Combined`<=0.01)
df<-filter(df,Master=="Master Protein")

df2<-readRDS("/media/sf_wheat-soil/soilprotein/panama/PanamaMeta2/panamameMeta2ProteinsFix.xlsx.rds")
df2<-filter(df2,Contaminant==F,`Exp..q-value:.Combined`<=0.01)
df2<-filter(df2,Master=="Master Protein")

# P-Deficiency vs P-rich more,less, default is all
extractDP<-function(tempDF,judgeMode,judge="both") {
  FDRName<-paste0("Abundance.Ratio.Adj..P-Value:.",judgeMode)
  FCName<-paste0("Abundance.Ratio:.",judgeMode)
  df<-filter(tempDF,!is.na(tempDF[,FDRName]),!is.na(tempDF[,FCName]))[,c("Accession",FDRName,FCName)]
  colnames(df)[2:3]<-c("FDR","FD")
  # The Standard of significance was more than 2 times, P value was 0.05
  if(judge=="more"){df<-filter(df,FD>=2,FDR<=0.05)}
  if(judge=="less"){df<-filter(df,FD<=2,FDR<=0.05)}
  else{df<-filter(df,FD>=2 | FD<=1/2, FDR<=0.05)}
  return(df)
}

df3<-extractDP(df,"(low)./.(high)")
write.table(df3$Accession,"panamaNCBIdifferentPortein.txt",quote = F,row.names = F,col.names = F)
df3<-extractDP(df,"(low)./.(high)","more")
write.table(df3$Accession,"panamaNCBIdifferentPorteinMore.txt",quote = F,row.names = F,col.names = F)
df3<-extractDP(df,"(low)./.(high)","less")
write.table(df3$Accession,"panamaNCBIdifferentPorteinLess.txt",quote = F,row.names = F,col.names = F)

df3<-extractDP(df2,"(low)./.(high)")
write.table(df3$Accession,"panamaMetaDifferentPortein.txt",quote = F,row.names = F,col.names = F)
df3<-extractDP(df2,"(low)./.(high)","more")
write.table(df3$Accession,"panamaMetaDifferentPorteinMore.txt",quote = F,row.names = F,col.names = F)
df3<-extractDP(df2,"(low)./.(high)","less")
write.table(df3$Accession,"panamaMetaDifferentPorteinLess.txt",quote = F,row.names = F,col.names = F)
```


### Extract annotations from blast2go Annotation Results and perform enrichment analysis

#### Public DB

```{r}
NCBIgo<-read.table("panamaNCBIgoTerm.txt",sep="\t",header=T,stringsAsFactors=F)
# Remove unannotated proteins
NCBIgo<-NCBIgo[NCBIgo$GO.IDs!="",]
# Split a single comment multiple items
NCBIgo<-tidyr::separate_rows(NCBIgo,GO.IDs,sep="; ")
# Separate MF，BP，CC
library(stringr)
NCBIgo<-cbind(NCBIgo,Ont=str_sub(NCBIgo$GO.IDs,1L,1L))
NCBIgo$GO.IDs<-str_sub(NCBIgo$GO.IDs,3L)
library(clusterProfiler)
goMapBp <- buildGOmap(NCBIgo[NCBIgo$Ont == "P",2:1])
goMapMf <- buildGOmap(NCBIgo[NCBIgo$Ont == "F",2:1])
goMapCc <- buildGOmap(NCBIgo[NCBIgo$Ont == "C",2:1])
saveRDS(goMapBp,"ncbiGoMapBp.rds")
saveRDS(goMapMf,"ncbiGoMapMf.rds")
saveRDS(goMapCc,"ncbiGoMapCc.rds")
goMapBp <- readRDS("ncbiGoMapBp.rds")
goMapMf <- readRDS("ncbiGoMapMf.rds")
goMapCc <- readRDS("ncbiGoMapCc.rds")
library(GO.db)
# columns(GO.db) You can see which terms you can extract
goNameBP <- AnnotationDbi::select(x=GO.db, keys = goMapBp$GO,  keytype = "GOID",columns = "TERM" )
goNameMf <- AnnotationDbi::select(x=GO.db, keys = goMapMf$GO,  keytype = "GOID",columns = "TERM" )
goNameCc <- AnnotationDbi::select(x=GO.db, keys = goMapCc$GO,  keytype = "GOID",columns = "TERM" )
df1<-read.table("/media/sf_wheat-soil/soilprotein/panama/panamaNCBIdifferentPorteinMore.txt")
df2<-read.table("/media/sf_wheat-soil/soilprotein/panama/panamaNCBIdifferentPorteinLess.txt")
df3<-read.table("/media/sf_wheat-soil/soilprotein/panama/panamaNCBIdifferentPortein.txt")
# To map up and down biological processes
library(ggplot2)
goBP <- merge_result(list(up= enricher(df1$V1,TERM2GENE = goMapBp, TERM2NAME=goNameBP),
                          down=enricher(df2$V1,TERM2GENE = goMapBp, TERM2NAME=goNameBP)))
dotplot(goBP,font.size=10)
# Draw up-regulated proteins separately
goBp <- enricher(df1$V1,TERM2GENE = goMapBp, TERM2NAME=goNameBP)
goMf <- enricher(df1$V1,TERM2GENE = goMapMf, TERM2NAME=goNameMf)
goCc <- enricher(df1$V1,TERM2GENE = goMapCc, TERM2NAME=goNameCc)
xlsx::write.xlsx(as.data.frame(goBp),"ncbiGoBp.xlsx")
xlsx::write.xlsx(as.data.frame(goMf),"ncbigoMf.xlsx")
xlsx::write.xlsx(as.data.frame(goCc),"ncbigoCc.xlsx")
```

#### Meta DB

```{r}
metaGo<-read.table("panamaMetaGoTerm.txt",sep="\t",header=T,stringsAsFactors=F)
metaGo<-metaGo[metaGo$GO.IDs!="",]
metaGo<-tidyr::separate_rows(metaGo,GO.IDs,sep="; ")
library(stringr)
metaGo<-cbind(metaGo,Ont=str_sub(metaGo$GO.IDs,1L,1L))
metaGo$GO.IDs<-str_sub(metaGo$GO.IDs,3L)
library(clusterProfiler)
goMapBp <- buildGOmap(metaGo[metaGo$Ont == "P",2:1])
goMapMf <- buildGOmap(metaGo[metaGo$Ont == "F",2:1])
goMapCc <- buildGOmap(metaGo[metaGo$Ont == "C",2:1])
saveRDS(goMapBp,"MetaGoMapBp.rds")
saveRDS(goMapMf,"MetaGoMapMf.rds")
saveRDS(goMapCc,"MetaGoMapCc.rds")
library(GO.db)
goNameBP <- AnnotationDbi::select(x=GO.db, keys = goMapBp$GO,  keytype = "GOID",columns = "TERM" )
goNameMf <- AnnotationDbi::select(x=GO.db, keys = goMapMf$GO,  keytype = "GOID",columns = "TERM" )
goNameCc <- AnnotationDbi::select(x=GO.db, keys = goMapCc$GO,  keytype = "GOID",columns = "TERM" )
df1<-read.table("panamaMetaDifferentPorteinMore.txt")
df2<-read.table("panamaMetaDifferentPorteinLess.txt")
df3<-read.table("panamaMetaDifferentPortein.txt")
library(ggplot2)
goBP <- merge_result(list(up= enricher(df1$V1,TERM2GENE = goMapBp, TERM2NAME=goNameBP),
                          down=enricher(df2$V1,TERM2GENE = goMapBp, TERM2NAME=goNameBP)))
dotplot(goBP,font.size=10)
goBp <- enricher(df1$V1,TERM2GENE = goMapBp, TERM2NAME=goNameBP)
goMf <- enricher(df1$V1,TERM2GENE = goMapMf, TERM2NAME=goNameMf)
goCc <- enricher(df1$V1,TERM2GENE = goMapCc, TERM2NAME=goNameCc,pvalueCutoff = 0.5)
xlsx::write.xlsx(as.data.frame(goBp),"metaGoBp.xlsx")
xlsx::write.xlsx(as.data.frame(goMf),"metagoMf.xlsx")
```

### draw GoBp and GoMf results of the 2 DB in one figure

#### GoBp

```{r}
library(readxl)
library(tidyverse)
library(ggplot2)
ncbiGoBp<-read_xlsx("ncbiGoBp.xlsx",range = cell_cols(2:9))
metaGoBp<-read_xlsx("metaGoBp.xlsx",range = cell_cols(2:9))
# First, merge the two tables
GoBp<-rbind(cbind(ncbiGoBp,database="ncbi"),cbind(metaGoBp,database="meta"))[,c(1:3,6,9)]
GoBpDraw<-separate(GoBp,GeneRatio,c("up","all"),sep="/")
GoBpDraw[,3:4]<-lapply(GoBpDraw[,3:4],as.numeric)
GoBpDraw<-mutate(GoBpDraw,ratio=up/all)
GoBpDraw$database<-factor(GoBpDraw$database,levels = c("meta","ncbi"))
ggplot(GoBpDraw, aes(x=Description, y=ratio, size=up)) + 
  geom_point(aes(colour = p.adjust))+coord_flip()+facet_grid(cols = vars(database)) +
  scale_colour_gradient(low = "red", high ="blue") +
  theme(text = element_text(size=15))+
  scale_x_discrete(labels=function(x) str_wrap(x, width=15))+
  ggsave("ncbiAndMetaGoBp.svg",width =10.24,height = 7.68,dpi = 100)

# First, gather columns that we need to merge
GoBp<-gather(GoBp,variable, value, -database,-ID,-Description)
# Hang the variable name on the table name
GoBp<-unite(GoBp,temp, database, variable)
# Split the gathered column by the merged variable name
GoBp<-spread(GoBp,temp, value)
xlsx::write.xlsx(GoBp,"ncbiAndMetaGoBp.xlsx",row.names=F)
```

#### GoMf

```{r}
ncbiGoMf<-read_xlsx("ncbiGoMf.xlsx",range = cell_cols(2:9))
metaGoMf<-read_xlsx("metaGoMf.xlsx",range = cell_cols(2:9))
GoMf<-rbind(cbind(ncbiGoMf,database="ncbi"),cbind(metaGoMf,database="meta"))[,c(1:3,6,9)]
GoMfDraw<-separate(GoMf,GeneRatio,c("up","all"),sep="/")
GoMfDraw[,3:4]<-lapply(GoMfDraw[,3:4],as.numeric)
GoMfDraw<-mutate(GoMfDraw,ratio=up/all)
GoMfDraw$database<-factor(GoMfDraw$database,levels = c("meta","ncbi"))
ggplot(GoMfDraw, aes(x=Description, y=ratio, size=up)) + 
  geom_point(aes(colour = p.adjust))+coord_flip()+facet_grid(cols = vars(database)) +
  scale_colour_gradient(low = "red", high ="blue") +
ggsave("ncbiAndMetaGoMf.png",width =10.24,height = 7.68,dpi = 100)

ggplot(GoMfDraw, aes(x=Description, y=ratio, size=up)) + 
  geom_point(aes(colour = p.adjust))+coord_flip()+facet_grid(cols = vars(database)) +
  scale_colour_gradient(low = "red", high ="blue") +
  theme(text = element_text(size=15))+
  scale_x_discrete(labels=function(x) str_wrap(x, width=15))+
  ggsave("ncbiAndMetaGoMf.svg",width =12.80,height = 7.68,dpi = 100)

GoMf<-gather(GoMf,variable, value, -database,-ID,-Description)
GoMf<-unite(GoMf,temp, database, variable)
GoMf<-spread(GoMf,temp, value)
xlsx::write.xlsx(GoMf,"ncbiAndMetaGoMf.xlsx")
```
